run:
  timeout: 5m
  output:
    format: tab
  tests: false

linters-settings:
  govet:
    enable:
      - shadow
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain

linters:
  enable:
    - revive
    - govet
    - unconvert
    - unused
    - gosec
    - dupl
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - gosimple
    - staticcheck
    - unused
    - copyloopvar
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment"
      linters:
        - revive
    - path: _test\.go
      linters:
        - gosec
        - dupl
  exclude-dirs:
    - vendor

  exclude-use-default: false

