// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ayankousky/exchange-data-importer/internal/infrastructure/notify"
	"sync"
)

// ClientMock is a mock implementation of notify.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked notify.Client
//		mockedClient := &ClientMock{
//			SendFunc: func(ctx context.Context, event notify.Event) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedClient in code that requires notify.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, event notify.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event notify.Event
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *ClientMock) Send(ctx context.Context, event notify.Event) error {
	if mock.SendFunc == nil {
		panic("ClientMock.SendFunc: method is nil but Client.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event notify.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedClient.SendCalls())
func (mock *ClientMock) SendCalls() []struct {
	Ctx   context.Context
	Event notify.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event notify.Event
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// ResetSendCalls reset all the calls that were made to Send.
func (mock *ClientMock) ResetSendCalls() {
	mock.lockSend.Lock()
	mock.calls.Send = nil
	mock.lockSend.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ClientMock) ResetCalls() {
	mock.lockSend.Lock()
	mock.calls.Send = nil
	mock.lockSend.Unlock()
}
