name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: build and deploy image to ghcr.io
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GHCR_LOGIN }}
          USERNAME: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha}}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Building version ${VERSION}"
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push \
              --target release \
              --build-arg CI=github \
              --build-arg GITHUB_SHA=${GITHUB_SHA} \
              --build-arg VERSION=${VERSION} \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              -t ghcr.io/${USERNAME}/exchange-importer:${VERSION} \
              -t ghcr.io/${USERNAME}/exchange-importer:latest .